name: build

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/MeIsReallyBa/padavan-4.4
  REPO_BRANCH: main
  TNAME: RM2100

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Clone source
      run: |
        git clone --depth=1 $REPO_URL -b $REPO_BRANCH /opt/rt-n56u

    - name: Customize config
      run: |
        mv -f $TNAME.config /opt/rt-n56u/trunk/configs/templates/$TNAME.config

    - name: Prepare environment
      run: |
        sudo apt update
        sudo apt install libtool-bin gperf python3-docutils autopoint gettext

    - name: Run shellcheck
      run: sh /opt/rt-n56u/trunk/tools/shellcheck.sh

    - name: Prepare toolchain
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh

    - name: Start build
      run: |
        cd /opt/rt-n56u/trunk
        fakeroot ./build_firmware_modify $TNAME 0

    - name: Set release date
      run: |
        echo "RELEASE_DATE=$(date +'%Y%m%d')" >> ${GITHUB_ENV}

    - name: Upload image to artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.TNAME }}_${{ env.RELEASE_DATE }}
        path: /opt/rt-n56u/trunk/images

    - name: Upload image to release
      uses: softprops/action-gh-release@v1
      with:
       tag_name: ${{ env.TNAME }}_${{ env.RELEASE_DATE }}
       files: |
        /opt/rt-n56u/trunk/images/*.trx
